import React, { useState, useEffect } from 'react';

const CityList = ({ onCitySelect }) => {
  const [cities, setCities] = useState([
    { _id: '1', name: "Abidjan", country: "Côte d'Ivoire", countryCode: "CI" },
    { _id: '2', name: "Abuja", country: "Nigeria", countryCode: "NG" },
    { _id: '3', name: "Accra", country: "Ghana", countryCode: "GH" },
    { _id: '4', name: "Adelaide", country: "Australia", countryCode: "AU" },
    { _id: '5', name: "Adilabad", country: "India", countryCode: "IN" },
    { _id: '6', name: "Agartala", country: "India", countryCode: "IN" },
    { _id: '7', name: "Agra", country: "India", countryCode: "IN" },
    { _id: '8', name: "Ahmedabad", country: "India", countryCode: "IN" },
    { _id: '9', name: "Ahmednagar", country: "India", countryCode: "IN" },
    { _id: '10', name: "Aizawl", country: "India", countryCode: "IN" },
    { _id: '11', name: "Ajmer", country: "India", countryCode: "IN" },
    { _id: '12', name: "Akola", country: "India", countryCode: "IN" },
    { _id: '13', name: "Aleppo", country: "Syria", countryCode: "SY" },
    { _id: '14', name: "Alexandria", country: "Egypt", countryCode: "EG" },
    { _id: '15', name: "Aligarh", country: "India", countryCode: "IN" },
    { _id: '16', name: "Alappuzha", country: "India", countryCode: "IN" },
    { _id: '17', name: "Algiers", country: "Algeria", countryCode: "DZ" },
    { _id: '18', name: "Allahabad", country: "India", countryCode: "IN" },
    { _id: '19', name: "Almora", country: "India", countryCode: "IN" },
    { _id: '20', name: "Alwar", country: "India", countryCode: "IN" },
    { _id: '21', name: "Amaravati", country: "India", countryCode: "IN" },
    { _id: '22', name: "Ambala", country: "India", countryCode: "IN" },
    { _id: '23', name: "Ambedkar Nagar", country: "India", countryCode: "IN" },
    { _id: '24', name: "Amman", country: "Jordan", countryCode: "JO" },
    { _id: '25', name: "Amravati", country: "India", countryCode: "IN" },
    { _id: '26', name: "Amreli", country: "India", countryCode: "IN" },
    { _id: '27', name: "Amritsar", country: "India", countryCode: "IN" },
    { _id: '28', name: "Anand", country: "India", countryCode: "IN" },
    { _id: '29', name: "Anantapur", country: "India", countryCode: "IN" },
    { _id: '30', name: "Ankara", country: "Turkey", countryCode: "TR" },
    { _id: '31', name: "Ankleshwar", country: "India", countryCode: "IN" },
    { _id: '32', name: "Antananarivo", country: "Madagascar", countryCode: "MG" },
    { _id: '33', name: "Arrah", country: "India", countryCode: "IN" },
    { _id: '34', name: "Asansol", country: "India", countryCode: "IN" },
    { _id: '35', name: "Ashgabat", country: "Turkmenistan", countryCode: "TM" },
    { _id: '36', name: "Asmara", country: "Eritrea", countryCode: "ER" },
    { _id: '37', name: "Atlanta", country: "USA", countryCode: "US" },
    { _id: '38', name: "Auckland", country: "New Zealand", countryCode: "NZ" },
    { _id: '39', name: "Aurangabad", country: "India", countryCode: "IN" },
    { _id: '40', name: "Azamgarh", country: "India", countryCode: "IN" },
    { _id: '41', name: "Baghdad", country: "Iraq", countryCode: "IQ" },
    { _id: '42', name: "Bahraich", country: "India", countryCode: "IN" },
    { _id: '43', name: "Baku", country: "Azerbaijan", countryCode: "AZ" },
    { _id: '44', name: "Balangir", country: "India", countryCode: "IN" },
    { _id: '45', name: "Balasore", country: "India", countryCode: "IN" },
    { _id: '46', name: "Ballia", country: "India", countryCode: "IN" },
    { _id: '47', name: "Bamako", country: "Mali", countryCode: "ML" },
    { _id: '48', name: "Banda", country: "India", countryCode: "IN" },
    { _id: '49', name: "Bandung", country: "Indonesia", countryCode: "ID" },
    { _id: '50', name: "Bangalore", country: "India", countryCode: "IN" },
    { _id: '51', name: "Bangkok", country: "Thailand", countryCode: "TH" },
    { _id: '52', name: "Bangui", country: "Central African Republic", countryCode: "CF" },
    { _id: '53', name: "Bankura", country: "India", countryCode: "IN" },
    { _id: '54', name: "Banswara", country: "India", countryCode: "IN" },
    { _id: '55', name: "Baramulla", country: "India", countryCode: "IN" },
    { _id: '56', name: "Barcelona", country: "Spain", countryCode: "ES" },
    { _id: '57', name: "Barddhaman", country: "India", countryCode: "IN" },
    { _id: '58', name: "Bareilly", country: "India", countryCode: "IN" },
    { _id: '59', name: "Barmer", country: "India", countryCode: "IN" },
    { _id: '60', name: "Barnala", country: "India", countryCode: "IN" },
    { _id: '61', name: "Barpeta", country: "India", countryCode: "IN" },
    { _id: '62', name: "Barranquilla", country: "Colombia", countryCode: "CO" },
    { _id: '63', name: "Basrah", country: "Iraq", countryCode: "IQ" },
    { _id: '64', name: "Basti", country: "India", countryCode: "IN" },
    { _id: '65', name: "Batala", country: "India", countryCode: "IN" },
    { _id: '66', name: "Beed", country: "India", countryCode: "IN" },
    { _id: '67', name: "Begusarai", country: "India", countryCode: "IN" },
    { _id: '68', name: "Beirut", country: "Lebanon", countryCode: "LB" },
    { _id: '69', name: "Belgaum", country: "India", countryCode: "IN" },
    { _id: '70', name: "Belo Horizonte", country: "Brazil", countryCode: "BR" },
    { _id: '71', name: "Bellary", country: "India", countryCode: "IN" },
    { _id: '72', name: "Berlin", country: "Germany", countryCode: "DE" },
    { _id: '73', name: "Berhampur", country: "India", countryCode: "IN" },
    { _id: '74', name: "Bettiah", country: "India", countryCode: "IN" },
    { _id: '75', name: "Bhadrak", country: "India", countryCode: "IN" },
    { _id: '76', name: "Bhagalpur", country: "India", countryCode: "IN" },
    { _id: '77', name: "Bhandara", country: "India", countryCode: "IN" },
    { _id: '78', name: "Bharatpur", country: "India", countryCode: "IN" },
    { _id: '79', name: "Bhavnagar", country: "India", countryCode: "IN" },
    { _id: '80', name: "Bhilai", country: "India", countryCode: "IN" },
    { _id: '81', name: "Bhilwara", country: "India", countryCode: "IN" },
    { _id: '82', name: "Bhind", country: "India", countryCode: "IN" },
    { _id: '83', name: "Bhiwandi", country: "India", countryCode: "IN" },
    { _id: '84', name: "Bhiwani", country: "India", countryCode: "IN" },
    { _id: '85', name: "Bhopal", country: "India", countryCode: "IN" },
    { _id: '86', name: "Bhubaneswar", country: "India", countryCode: "IN" },
    { _id: '87', name: "Bikaner", country: "India", countryCode: "IN" },
    { _id: '88', name: "Bilaspur", country: "India", countryCode: "IN" },
    { _id: '89', name: "Bokaro", country: "India", countryCode: "IN" },
    { _id: '90', name: "Bongaigaon", country: "India", countryCode: "IN" },
    { _id: '91', name: "Boston", country: "USA", countryCode: "US" },
    { _id: '92', name: "Botad", country: "India", countryCode: "IN" },
    { _id: '93', name: "Brasília", country: "Brazil", countryCode: "BR" },
    { _id: '94', name: "Brisbane", country: "Australia", countryCode: "AU" },
    { _id: '95', name: "Budaun", country: "India", countryCode: "IN" },
    { _id: '96', name: "Buenos Aires", country: "Argentina", countryCode: "AR" },
    { _id: '97', name: "Bulandshahr", country: "India", countryCode: "IN" },
    { _id: '98', name: "Bundi", country: "India", countryCode: "IN" },
    { _id: '99', name: "Burhanpur", country: "India", countryCode: "IN" },
    { _id: '100', name: "Bursa", country: "Turkey", countryCode: "TR" },
    { _id: '101', name: "Busan", country: "South Korea", countryCode: "KR" },
    { _id: '102', name: "Buxar", country: "India", countryCode: "IN" },
    { _id: '103', name: "Cairo", country: "Egypt", countryCode: "EG" },
    { _id: '104', name: "Calgary", country: "Canada", countryCode: "CA" },
    { _id: '105', name: "Campinas", country: "Brazil", countryCode: "BR" },
    { _id: '106', name: "Cape Town", country: "South Africa", countryCode: "ZA" },
    { _id: '107', name: "Caracas", country: "Venezuela", countryCode: "VE" },
    { _id: '108', name: "Casablanca", country: "Morocco", countryCode: "MA" },
    { _id: '109', name: "Chandigarh", country: "India", countryCode: "IN" },
    { _id: '110', name: "Chandrapur", country: "India", countryCode: "IN" },
    { _id: '111', name: "Chengdu", country: "China", countryCode: "CN" },
    { _id: '112', name: "Chennai", country: "India", countryCode: "IN" },
    { _id: '113', name: "Chhapra", country: "India", countryCode: "IN" },
    { _id: '114', name: "Chhindwara", country: "India", countryCode: "IN" },
    { _id: '115', name: "Chidambaram", country: "India", countryCode: "IN" },
    { _id: '116', name: "Chikkamagaluru", country: "India", countryCode: "IN" },
    { _id: '117', name: "Chittoor", country: "India", countryCode: "IN" },
    { _id: '118', name: "Chongqing", country: "China", countryCode: "CN" },
    { _id: '119', name: "Christchurch", country: "New Zealand", countryCode: "NZ" },
    { _id: '120', name: "Coimbatore", country: "India", countryCode: "IN" },
    { _id: '121', name: "Conakry", country: "Guinea", countryCode: "GN" },
    { _id: '122', name: "Cuddalore", country: "India", countryCode: "IN" },
    { _id: '123', name: "Curitiba", country: "Brazil", countryCode: "BR" },
    { _id: '124', name: "Cuttack", country: "India", countryCode: "IN" },
    { _id: '125', name: "Da Nang", country: "Vietnam", countryCode: "VN" },
    { _id: '126', name: "Dakar", country: "Senegal", countryCode: "SN" },
    { _id: '127', name: "Dalian", country: "China", countryCode: "CN" },
    { _id: '128', name: "Dallas", country: "USA", countryCode: "US" },
    { _id: '129', name: "Daltonganj", country: "India", countryCode: "IN" },
    { _id: '130', name: "Daman", country: "India", countryCode: "IN" },
    { _id: '131', name: "Damascus", country: "Syria", countryCode: "SY" },
    { _id: '132', name: "Damoh", country: "India", countryCode: "IN" },
    { _id: '133', name: "Dar Es Salaam", country: "Tanzania", countryCode: "TZ" },
    { _id: '134', name: "Darbhanga", country: "India", countryCode: "IN" },
    { _id: '135', name: "Darjeeling", country: "India", countryCode: "IN" },
    { _id: '136', name: "Davanagere", country: "India", countryCode: "IN" },
    { _id: '137', name: "Dehradun", country: "India", countryCode: "IN" },
    { _id: '138', name: "Delhi", country: "India", countryCode: "IN" },
    { _id: '139', name: "Deoria", country: "India", countryCode: "IN" },
    { _id: '140', name: "Dewas", country: "India", countryCode: "IN" },
    { _id: '141', name: "Dhaka", country: "Bangladesh", countryCode: "BD" },
    { _id: '142', name: "Dhanbad", country: "India", countryCode: "IN" },
    { _id: '143', name: "Dhar", country: "India", countryCode: "IN" },
    { _id: '144', name: "Dharmapuri", country: "India", countryCode: "IN" },
    { _id: '145', name: "Dharwad", country: "India", countryCode: "IN" },
    { _id: '146', name: "Dhenkanal", country: "India", countryCode: "IN" },
    { _id: '147', name: "Dhule", country: "India", countryCode: "IN" },
    { _id: '148', name: "Dibrugarh", country: "India", countryCode: "IN" },
    { _id: '149', name: "Dimapur", country: "India", countryCode: "IN" },
    { _id: '150', name: "Dindigul", country: "India", countryCode: "IN" },
    { _id: '151', name: "Diu", country: "India", countryCode: "IN" },
    { _id: '152', name: "Doha", country: "Qatar", countryCode: "QA" },
    { _id: '153', name: "Douala", country: "Cameroon", countryCode: "CM" },
    { _id: '154', name: "Dubai", country: "UAE", countryCode: "AE" },
    { _id: '155', name: "Durg", country: "India", countryCode: "IN" },
    { _id: '156', name: "Durgapur", country: "India", countryCode: "IN" },
    { _id: '157', name: "Edmonton", country: "Canada", countryCode: "CA" },
    { _id: '158', name: "Eluru", country: "India", countryCode: "IN" },
    { _id: '159', name: "Erode", country: "India", countryCode: "IN" },
    { _id: '160', name: "Etah", country: "India", countryCode: "IN" },
    { _id: '161', name: "Etawah", country: "India", countryCode: "IN" },
    { _id: '162', name: "Faizabad", country: "India", countryCode: "IN" },
    { _id: '163', name: "Faridabad", country: "India", countryCode: "IN" },
    { _id: '164', name: "Faridkot", country: "India", countryCode: "IN" },
    { _id: '165', name: "Farrukhabad", country: "India", countryCode: "IN" },
    { _id: '166', name: "Fatehpur", country: "India", countryCode: "IN" },
    { _id: '167', name: "Firozabad", country: "India", countryCode: "IN" },
    { _id: '168', name: "Firozpur", country: "India", countryCode: "IN" },
    { _id: '169', name: "Fortaleza", country: "Brazil", countryCode: "BR" },
    { _id: '170', name: "Freetown", country: "Sierra Leone", countryCode: "SL" },
    { _id: '171', name: "Fukuoka", country: "Japan", countryCode: "JP" },
    { _id: '172', name: "Fuzhou", country: "China", countryCode: "CN" },
    { _id: '173', name: "Gadag", country: "India", countryCode: "IN" },
    { _id: '174', name: "Gandhidham", country: "India", countryCode: "IN" },
    { _id: '175', name: "Gandhinagar", country: "India", countryCode: "IN" },
    { _id: '176', name: "Ganganagar", country: "India", countryCode: "IN" },
    { _id: '177', name: "Gangtok", country: "India", countryCode: "IN" },
    { _id: '178', name: "Gaya", country: "India", countryCode: "IN" },
    { _id: '179', name: "Ghaziabad", country: "India", countryCode: "IN" },
    { _id: '180', name: "Ghazipur", country: "India", countryCode: "IN" },
    { _id: '181', name: "Giza", country: "Egypt", countryCode: "EG" },
    { _id: '182', name: "Giridih", country: "India", countryCode: "IN" },
    { _id: '183', name: "Goa", country: "India", countryCode: "IN" },
    { _id: '184', name: "Godhra", country: "India", countryCode: "IN" },
    { _id: '185', name: "Goiânia", country: "Brazil", countryCode: "BR" },
    { _id: '186', name: "Gonda", country: "India", countryCode: "IN" },
    { _id: '187', name: "Gorakhpur", country: "India", countryCode: "IN" },
    { _id: '188', name: "Guangzhou", country: "China", countryCode: "CN" },
    { _id: '189', name: "Guatemala City", country: "Guatemala", countryCode: "GT" },
    { _id: '190', name: "Guayaquil", country: "Ecuador", countryCode: "EC" },
    { _id: '191', name: "Gulbarga", country: "India", countryCode: "IN" },
    { _id: '192', name: "Guntur", country: "India", countryCode: "IN" },
    { _id: '193', name: "Gurgaon", country: "India", countryCode: "IN" },
    { _id: '194', name: "Guwahati", country: "India", countryCode: "IN" },
    { _id: '195', name: "Gwalior", country: "India", countryCode: "IN" },
    { _id: '196', name: "Haldia", country: "India", countryCode: "IN" },
    { _id: '197', name: "Haldwani", country: "India", countryCode: "IN" },
    { _id: '198', name: "Hamirpur", country: "India", countryCode: "IN" },
    { _id: '199', name: "Hangzhou", country: "China", countryCode: "CN" },
    { _id: '200', name: "Hanoi", country: "Vietnam", countryCode: "VN" },
    { _id: '201', name: "Hapur", country: "India", countryCode: "IN" },
    { _id: '202', name: "Harare", country: "Zimbabwe", countryCode: "ZW" },
    { _id: '203', name: "Hardoi", country: "India", countryCode: "IN" },
    { _id: '204', name: "Haridwar", country: "India", countryCode: "IN" },
    { _id: '205', name: "Hassan", country: "India", countryCode: "IN" },
    { _id: '206', name: "Hathras", country: "India", countryCode: "IN" },
    { _id: '207', name: "Havana", country: "Cuba", countryCode: "CU" },
    { _id: '208', name: "Haveri", country: "India", countryCode: "IN" },
    { _id: '209', name: "Hazaribagh", country: "India", countryCode: "IN" },
    { _id: '210', name: "Hindaun", country: "India", countryCode: "IN" },
    { _id: '211', name: "Hinganghat", country: "India", countryCode: "IN" },
    { _id: '212', name: "Hisar", country: "India", countryCode: "IN" },
    { _id: '213', name: "Ho Chi Minh City", country: "Vietnam", countryCode: "VN" },
    { _id: '214', name: "Hong Kong", country: "China", countryCode: "HK" },
    { _id: '215', name: "Honolulu", country: "USA", countryCode: "US" },
    { _id: '216', name: "Hoshangabad", country: "India", countryCode: "IN" },
    { _id: '217', name: "Hoshiarpur", country: "India", countryCode: "IN" },
    { _id: '218', name: "Houston", country: "USA", countryCode: "US" },
    { _id: '219', name: "Howrah", country: "India", countryCode: "IN" },
    { _id: '220', name: "Hubli-Dharwad", country: "India", countryCode: "IN" },
    { _id: '221', name: "Hyderabad", country: "India", countryCode: "IN" },
    { _id: '222', name: "Ibadan", country: "Nigeria", countryCode: "NG" },
    { _id: '223', name: "Imphal", country: "India", countryCode: "IN" },
    { _id: '224', name: "Incheon", country: "South Korea", countryCode: "KR" },
    { _id: '225', name: "Indore", country: "India", countryCode: "IN" },
    { _id: '226', name: "Istanbul", country: "Turkey", countryCode: "TR" },
    { _id: '227', name: "Itanagar", country: "India", countryCode: "IN" },
    { _id: '228', name: "Izmir", country: "Turkey", countryCode: "TR" },
    { _id: '229', name: "Jabalpur", country: "India", countryCode: "IN" },
    { _id: '230', name: "Jaipur", country: "India", countryCode: "IN" },
    { _id: '231', name: "Jaisalmer", country: "India", countryCode: "IN" },
    { _id: '232', name: "Jakarta", country: "Indonesia", countryCode: "ID" },
    { _id: '233', name: "Jalandhar", country: "India", countryCode: "IN" },
    { _id: '234', name: "Jalgaon", country: "India", countryCode: "IN" },
    { _id: '235', name: "Jalna", country: "India", countryCode: "IN" },
    { _id: '236', name: "Jalpaiguri", country: "India", countryCode: "IN" },
    { _id: '237', name: "Jammu", country: "India", countryCode: "IN" },
    { _id: '238', name: "Jamnagar", country: "India", countryCode: "IN" },
    { _id: '239', name: "Jamshedpur", country: "India", countryCode: "IN" },
    { _id: '240', name: "Jaunpur", country: "India", countryCode: "IN" },
    { _id: '241', name: "Jeddah", country: "Saudi Arabia", countryCode: "SA" },
    { _id: '242', name: "Jerusalem", country: "Israel", countryCode: "IL" },
    { _id: '243', name: "Jhansi", country: "India", countryCode: "IN" },
    { _id: '244', name: "Jhunjhunu", country: "India", countryCode: "IN" },
    { _id: '245', name: "Jind", country: "India", countryCode: "IN" },
    { _id: '246', name: "Jodhpur", country: "India", countryCode: "IN" },
    { _id: '247', name: "Johannesburg", country: "South Africa", countryCode: "ZA" },
    { _id: '248', name: "Jorhat", country: "India", countryCode: "IN" },
    { _id: '249', name: "Juba", country: "South Sudan", countryCode: "SS" },
    { _id: '250', name: "Junagadh", country: "India", countryCode: "IN" },
    { _id: '251', name: "Kadapa", country: "India", countryCode: "IN" },
    { _id: '252', name: "Kakinada", country: "India", countryCode: "IN" },
    { _id: '253', name: "Kalol", country: "India", countryCode: "IN" },
    { _id: '254', name: "Kalyan-Dombivli", country: "India", countryCode: "IN" },
    { _id: '255', name: "Kampala", country: "Uganda", countryCode: "UG" },
    { _id: '256', name: "Kano", country: "Nigeria", countryCode: "NG" },
    { _id: '257', name: "Kanchipuram", country: "India", countryCode: "IN" },
    { _id: '258', name: "Kandla", country: "India", countryCode: "IN" },
    { _id: '259', name: "Kangra", country: "India", countryCode: "IN" },
    { _id: '260', name: "Kannauj", country: "India", countryCode: "IN" },
    { _id: '261', name: "Kannur", country: "India", countryCode: "IN" },
    { _id: '262', name: "Kanpur", country: "India", countryCode: "IN" },
    { _id: '263', name: "Kanyakumari", country: "India", countryCode: "IN" },
    { _id: '264', name: "Kapurthala", country: "India", countryCode: "IN" },
    { _id: '265', name: "Karachi", country: "Pakistan", countryCode: "PK" },
    { _id: '266', name: "Karimnagar", country: "India", countryCode: "IN" },
    { _id: '267', name: "Karnal", country: "India", countryCode: "IN" },
    { _id: '268', name: "Karur", country: "India", countryCode: "IN" },
    { _id: '269', name: "Kasaragod", country: "India", countryCode: "IN" },
    { _id: '270', name: "Katihar", country: "India", countryCode: "IN" },
    { _id: '271', name: "Katni", country: "India", countryCode: "IN" },
    { _id: '272', name: "Khammam", country: "India", countryCode: "IN" },
    { _id: '273', name: "Khandwa", country: "India", countryCode: "IN" },
    { _id: '274', name: "Khargone", country: "India", countryCode: "IN" },
    { _id: '275', name: "Khartoum", country: "Sudan", countryCode: "SD" },
    { _id: '276', name: "Kheda", country: "India", countryCode: "IN" },
    { _id: '277', name: "Kishangarh", country: "India", countryCode: "IN" },
    { _id: '278', name: "Kochi", country: "India", countryCode: "IN" },
    { _id: '279', name: "Kohima", country: "India", countryCode: "IN" },
    { _id: '280', name: "Kolhapur", country: "India", countryCode: "IN" },
    { _id: '281', name: "Kolkata", country: "India", countryCode: "IN" },
    { _id: '282', name: "Kollam", country: "India", countryCode: "IN" },
    { _id: '283', name: "Korba", country: "India", countryCode: "IN" },
    { _id: '284', name: "Kota", country: "India", countryCode: "IN" },
    { _id: '285', name: "Kottayam", country: "India", countryCode: "IN" },
    { _id: '286', name: "Kozhikode", country: "India", countryCode: "IN" },
    { _id: '287', name: "Krishnanagar", country: "India", countryCode: "IN" },
    { _id: '288', name: "Kuala Lumpur", country: "Malaysia", countryCode: "MY" },
    { _id: '289', name: "Kumbakonam", country: "India", countryCode: "IN" },
    { _id: '290', name: "Kurnool", country: "India", countryCode: "IN" },
    { _id: '291', name: "Kurukshetra", country: "India", countryCode: "IN" },
    { _id: '292', name: "Kuwait City", country: "Kuwait", countryCode: "KW" },
    { _id: '293', name: "Lagos", country: "Nigeria", countryCode: "NG" },
    { _id: '294', name: "Lahore", country: "Pakistan", countryCode: "PK" },
    { _id: '295', name: "Lakhimpur", country: "India", countryCode: "IN" },
    { _id: '296', name: "La Paz", country: "Bolivia", countryCode: "BO" },
    { _id: '297', name: "Latur", country: "India", countryCode: "IN" },
    { _id: '298', name: "Lima", country: "Peru", countryCode: "PE" },
    { _id: '299', name: "London", country: "United Kingdom", countryCode: "GB" },
    { _id: '300', name: "Lomé", country: "Togo", countryCode: "TG" },
    { _id: '301', name: "Los Angeles", country: "USA", countryCode: "US" },
    { _id: '302', name: "Luanda", country: "Angola", countryCode: "AO" },
    { _id: '303', name: "Lucknow", country: "India", countryCode: "IN" },
    { _id: '304', name: "Ludhiana", country: "India", countryCode: "IN" },
    { _id: '305', name: "Lusaka", country: "Zambia", countryCode: "ZM" },
    { _id: '306', name: "Madurai", country: "India", countryCode: "IN" },
    { _id: '307', name: "Mahbubnagar", country: "India", countryCode: "IN" },
    { _id: '308', name: "Mainpuri", country: "India", countryCode: "IN" },
    { _id: '309', name: "Malappuram", country: "India", countryCode: "IN" },
    { _id: '310', name: "Manaus", country: "Brazil", countryCode: "BR" },
    { _id: '311', name: "Mandi", country: "India", countryCode: "IN" },
    { _id: '312', name: "Mangalore", country: "India", countryCode: "IN" },
    { _id: '313', name: "Manila", country: "Philippines", countryCode: "PH" },
    { _id: '314', name: "Maputo", country: "Mozambique", countryCode: "MZ" },
    { _id: '315', name: "Maracaibo", country: "Venezuela", countryCode: "VE" },
    { _id: '316', name: "Mathura", country: "India", countryCode: "IN" },
    { _id: '317', name: "Mau", country: "India", countryCode: "IN" },
    { _id: '318', name: "Mecca", country: "Saudi Arabia", countryCode: "SA" },
    { _id: '319', name: "Medan", country: "Indonesia", countryCode: "ID" },
    { _id: '320', name: "Medellín", country: "Colombia", countryCode: "CO" },
    { _id: '321', name: "Meerut", country: "India", countryCode: "IN" },
    { _id: '322', name: "Mehsana", country: "India", countryCode: "IN" },
    { _id: '323', name: "Melbourne", country: "Australia", countryCode: "AU" },
    { _id: '324', name: "Mexico City", country: "Mexico", countryCode: "MX" },
    { _id: '325', name: "Miami", country: "USA", countryCode: "US" },
    { _id: '326', name: "Mirzapur", country: "India", countryCode: "IN" },
    { _id: '327', name: "Moga", country: "India", countryCode: "IN" },
    { _id: '328', name: "Mogadishu", country: "Somalia", countryCode: "SO" },
    { _id: '329', name: "Monrovia", country: "Liberia", countryCode: "LR" },
    { _id: '330', name: "Montevideo", country: "Uruguay", countryCode: "UY" },
    { _id: '331', name: "Montreal", country: "Canada", countryCode: "CA" },
    { _id: '332', name: "Moradabad", country: "India", countryCode: "IN" },
    { _id: '333', name: "Morena", country: "India", countryCode: "IN" },
    { _id: '334', name: "Moscow", country: "Russia", countryCode: "RU" },
    { _id: '335', name: "Motihari", country: "India", countryCode: "IN" },
    { _id: '336', name: "Muktsar", country: "India", countryCode: "IN" },
    { _id: '337', name: "Mumbai", country: "India", countryCode: "IN" },
    { _id: '338', name: "Munger", country: "India", countryCode: "IN" },
    { _id: '339', name: "Muscat", country: "Oman", countryCode: "OM" },
    { _id: '340', name: "Muzaffarnagar", country: "India", countryCode: "IN" },
    { _id: '341', name: "Muzaffarpur", country: "India", countryCode: "IN" },
    { _id: '342', name: "Mysore", country: "India", countryCode: "IN" },
    { _id: '343', name: "Nadia", country: "India", countryCode: "IN" },
    { _id: '344', name: "Nagaon", country: "India", countryCode: "IN" },
    { _id: '345', name: "Nagaur", country: "India", countryCode: "IN" },
    { _id: '346', name: "Nagoya", country: "Japan", countryCode: "JP" },
    { _id: '347', name: "Nagpur", country: "India", countryCode: "IN" },
    { _id: '348', name: "Nairobi", country: "Kenya", countryCode: "KE" },
    { _id: '349', name: "Nanded", country: "India", countryCode: "IN" },
    { _id: '350', name: "Nandurbar", country: "India", countryCode: "IN" },
    { _id: '351', name: "Nandyal", country: "India", countryCode: "IN" },
    { _id: '352', name: "Nanjing", country: "China", countryCode: "CN" },
    { _id: '353', name: "Narsinghpur", country: "India", countryCode: "IN" },
    { _id: '354', name: "Nashik", country: "India", countryCode: "IN" },
    { _id: '355', name: "Navi Mumbai", country: "India", countryCode: "IN" },
    { _id: '356', name: "Navsari", country: "India", countryCode: "IN" },
    { _id: '357', name: "N'Djamena", country: "Chad", countryCode: "TD" },
    { _id: '358', name: "Nellore", country: "India", countryCode: "IN" },
    { _id: '359', name: "New York", country: "USA", countryCode: "US" },
    { _id: '360', name: "Niamey", country: "Niger", countryCode: "NE" },
    { _id: '361', name: "Ningbo", country: "China", countryCode: "CN" },
    { _id: '362', name: "Nizamabad", country: "India", countryCode: "IN" },
    { _id: '363', name: "Noida", country: "India", countryCode: "IN" },
    { _id: '364', name: "Nouakchott", country: "Mauritania", countryCode: "MR" },
    { _id: '365', name: "Ongole", country: "India", countryCode: "IN" },
    { _id: '366', name: "Osaka", country: "Japan", countryCode: "JP" },
    { _id: '367', name: "Ottawa", country: "Canada", countryCode: "CA" },
    { _id: '368', name: "Ouagadougou", country: "Burkina Faso", countryCode: "BF" },
    { _id: '369', name: "Palakkad", country: "India", countryCode: "IN" },
    { _id: '370', name: "Palanpur", country: "India", countryCode: "IN" },
    { _id: '371', name: "Pali", country: "India", countryCode: "IN" },
    { _id: '372', name: "Panaji", country: "India", countryCode: "IN" },
    { _id: '373', name: "Panchkula", country: "India", countryCode: "IN" },
    { _id: '374', name: "Panama City", country: "Panama", countryCode: "PA" },
    { _id: '375', name: "Panipat", country: "India", countryCode: "IN" },
    { _id: '376', name: "Parbhani", country: "India", countryCode: "IN" },
    { _id: '377', name: "Paris", country: "France", countryCode: "FR" },
    { _id: '378', name: "Patan", country: "India", countryCode: "IN" },
    { _id: '379', name: "Pathanamthitta", country: "India", countryCode: "IN" },
    { _id: '380', name: "Patiala", country: "India", countryCode: "IN" },
    { _id: '381', name: "Patna", country: "India", countryCode: "IN" },
    { _id: '382', name: "Perth", country: "Australia", countryCode: "AU" },
    { _id: '383', name: "Phnom Penh", country: "Cambodia", countryCode: "KH" },
    { _id: '384', name: "Phoenix", country: "USA", countryCode: "US" },
    { _id: '385', name: "Philadelphia", country: "USA", countryCode: "US" },
    { _id: '386', name: "Pilibhit", country: "India", countryCode: "IN" },
    { _id: '387', name: "Pondicherry", country: "India", countryCode: "IN" },
    { _id: '388', name: "Porbandar", country: "India", countryCode: "IN" },
    { _id: '389', name: "Port Blair", country: "India", countryCode: "IN" },
    { _id: '390', name: "Port Louis", country: "Mauritius", countryCode: "MU" },
    { _id: '391', name: "Port-au-Prince", country: "Haiti", countryCode: "HT" },
    { _id: '392', name: "Porto Alegre", country: "Brazil", countryCode: "BR" },
    { _id: '393', name: "Pratapgarh", country: "India", countryCode: "IN" },
    { _id: '394', name: "Pudukkottai", country: "India", countryCode: "IN" },
    { _id: '395', name: "Pune", country: "India", countryCode: "IN" },
    { _id: '396', name: "Puri", country: "India", countryCode: "IN" },
    { _id: '397', name: "Purnia", country: "India", countryCode: "IN" },
    { _id: '398', name: "Pyongyang", country: "North Korea", countryCode: "KP" },
    { _id: '399', name: "Quito", country: "Ecuador", countryCode: "EC" },
    { _id: '400', name: "Rabat", country: "Morocco", countryCode: "MA" },
    { _id: '401', name: "Raichur", country: "India", countryCode: "IN" },
    { _id: '402', name: "Raigarh", country: "India", countryCode: "IN" },
    { _id: '403', name: "Raipur", country: "India", countryCode: "IN" },
    { _id: '404', name: "Rajahmundry", country: "India", countryCode: "IN" },
    { _id: '405', name: "Rajkot", country: "India", countryCode: "IN" },
    { _id: '406', name: "Rajouri", country: "India", countryCode: "IN" },
    { _id: '407', name: "Rampur", country: "India", countryCode: "IN" },
    { _id: '408', name: "Ranchi", country: "India", countryCode: "IN" },
    { _id: '409', name: "Ratlam", country: "India", countryCode: "IN" },
    { _id: '410', name: "Ratnagiri", country: "India", countryCode: "IN" },
    { _id: '411', name: "Recife", country: "Brazil", countryCode: "BR" },
    { _id: '412', name: "Rewa", country: "India", countryCode: "IN" },
    { _id: '413', name: "Rewari", country: "India", countryCode: "IN" },
    { _id: '414', name: "Riyadh", country: "Saudi Arabia", countryCode: "SA" },
    { _id: '415', name: "Rio de Janeiro", country: "Brazil", countryCode: "BR" },
    { _id: '416', name: "Rohtak", country: "India", countryCode: "IN" },
    { _id: '417', name: "Rome", country: "Italy", countryCode: "IT" },
    { _id: '418', name: "Rourkela", country: "India", countryCode: "IN" },
    { _id: '419', name: "Sagar", country: "India", countryCode: "IN" },
    { _id: '420', name: "Saharanpur", country: "India", countryCode: "IN" },
    { _id: '421', name: "Saint Petersburg", country: "Russia", countryCode: "RU" },
    { _id: '422', name: "Salem", country: "India", countryCode: "IN" },
    { _id: '423', name: "Salvador", country: "Brazil", countryCode: "BR" },
    { _id: '424', name: "Sambalpur", country: "India", countryCode: "IN" },
    { _id: '425', name: "San Diego", country: "USA", countryCode: "US" },
    { _id: '426', name: "San Francisco", country: "USA", countryCode: "US" },
    { _id: '427', name: "San Salvador", country: "El Salvador", countryCode: "SV" },
    { _id: '428', name: "Sana'a", country: "Yemen", countryCode: "YE" },
    { _id: '429', name: "Sangli", country: "India", countryCode: "IN" },
    { _id: '430', name: "Sangrur", country: "India", countryCode: "IN" },
    { _id: '431', name: "Santiago", country: "Chile", countryCode: "CL" },
    { _id: '432', name: "Santo Domingo", country: "Dominican Republic", countryCode: "DO" },
    { _id: '433', name: "Sapporo", country: "Japan", countryCode: "JP" },
    { _id: '434', name: "São Paulo", country: "Brazil", countryCode: "BR" },
    { _id: '435', name: "Satara", country: "India", countryCode: "IN" },
    { _id: '436', name: "Satna", country: "India", countryCode: "IN" },
    { _id: '437', name: "Seattle", country: "USA", countryCode: "US" },
    { _id: '438', name: "Sehore", country: "India", countryCode: "IN" },
    { _id: '439', name: "Seoul", country: "South Korea", countryCode: "KR" },
    { _id: '440', name: "Shahjahanpur", country: "India", countryCode: "IN" },
    { _id: '441', name: "Shanghai", country: "China", countryCode: "CN" },
    { _id: '442', name: "Shenzhen", country: "China", countryCode: "CN" },
    { _id: '443', name: "Shillong", country: "India", countryCode: "IN" },
    { _id: '444', name: "Shimla", country: "India", countryCode: "IN" },
    { _id: '445', name: "Shimoga", country: "India", countryCode: "IN" },
    { _id: '446', name: "Sikar", country: "India", countryCode: "IN" },
    { _id: '447', name: "Silchar", country: "India", countryCode: "IN" },
    { _id: '448', name: "Siliguri", country: "India", countryCode: "IN" },
    { _id: '449', name: "Silvassa", country: "India", countryCode: "IN" },
    { _id: '450', name: "Singapore", country: "Singapore", countryCode: "SG" },
    { _id: '451', name: "Sirsa", country: "India", countryCode: "IN" },
    { _id: '452', name: "Sitamarhi", country: "India", countryCode: "IN" },
    { _id: '453', name: "Sitapur", country: "India", countryCode: "IN" },
    { _id: '454', name: "Sivakasi", country: "India", countryCode: "IN" },
    { _id: '455', name: "Siwan", country: "India", countryCode: "IN" },
    { _id: '456', name: "Solapur", country: "India", countryCode: "IN" },
    { _id: '457', name: "Sonipat", country: "India", countryCode: "IN" },
    { _id: '458', name: "Srinagar", country: "India", countryCode: "IN" },
    { _id: '459', name: "Sultanpur", country: "India", countryCode: "IN" },
    { _id: '460', name: "Surabaya", country: "Indonesia", countryCode: "ID" },
    { _id: '461', name: "Surat", country: "India", countryCode: "IN" },
    { _id: '462', name: "Surendranagar", country: "India", countryCode: "IN" },
    { _id: '463', name: "Sydney", country: "Australia", countryCode: "AU" },
    { _id: '464', name: "Tarn Taran", country: "India", countryCode: "IN" },
    { _id: '465', name: "Tashkent", country: "Uzbekistan", countryCode: "UZ" },
    { _id: '466', name: "Tbilisi", country: "Georgia", countryCode: "GE" },
    { _id: '467', name: "Tegucigalpa", country: "Honduras", countryCode: "HN" },
    { _id: '468', name: "Tehran", country: "Iran", countryCode: "IR" },
    { _id: '469', name: "Tel Aviv", country: "Israel", countryCode: "IL" },
    { _id: '470', name: "Tezpur", country: "India", countryCode: "IN" },
    { _id: '471', name: "Thane", country: "India", countryCode: "IN" },
    { _id: '472', name: "Thanjavur", country: "India", countryCode: "IN" },
    { _id: '473', name: "Thiruvananthapuram", country: "India", countryCode: "IN" },
    { _id: '474', name: "Thoothukudi", country: "India", countryCode: "IN" },
    { _id: '475', name: "Thrissur", country: "India", countryCode: "IN" },
    { _id: '476', name: "Tianjin", country: "China", countryCode: "CN" },
    { _id: '477', name: "Tinsukia", country: "India", countryCode: "IN" },
    { _id: '478', name: "Tiruchirappalli", country: "India", countryCode: "IN" },
    { _id: '479', name: "Tirunelveli", country: "India", countryCode: "IN" },
    { _id: '480', name: "Tirupati", country: "India", countryCode: "IN" },
    { _id: '481', name: "Tiruppur", country: "India", countryCode: "IN" },
    { _id: '482', name: "Tiruvallur", country: "India", countryCode: "IN" },
    { _id: '483', name: "Tiruvannamalai", country: "India", countryCode: "IN" },
    { _id: '484', name: "Tokyo", country: "Japan", countryCode: "JP" },
    { _id: '485', name: "Tonk", country: "India", countryCode: "IN" },
    { _id: '486', name: "Toronto", country: "Canada", countryCode: "CA" },
    { _id: '487', name: "Tripoli", country: "Libya", countryCode: "LY" },
    { _id: '488', name: "Tumkur", country: "India", countryCode: "IN" },
    { _id: '489', name: "Tunis", country: "Tunisia", countryCode: "TN" },
    { _id: '490', name: "Udaipur", country: "India", countryCode: "IN" },
    { _id: '491', name: "Udgir", country: "India", countryCode: "IN" },
    { _id: '492', name: "Udhampur", country: "India", countryCode: "IN" },
    { _id: '493', name: "Udupi", country: "India", countryCode: "IN" },
    { _id: '494', name: "Ujjain", country: "India", countryCode: "IN" },
    { _id: '495', name: "Ulhasnagar", country: "India", countryCode: "IN" },
    { _id: '496', name: "Unnao", country: "India", countryCode: "IN" },
    { _id: '497', name: "Ürümqi", country: "China", countryCode: "CN" },
    { _id: '498', name: "Vadodara", country: "India", countryCode: "IN" },
    { _id: '499', name: "Valsad", country: "India", countryCode: "IN" },
    { _id: '500', name: "Vancouver", country: "Canada", countryCode: "CA" },
    { _id: '501', name: "Varanasi", country: "India", countryCode: "IN" },
    { _id: '502', name: "Vasco da Gama", country: "India", countryCode: "IN" },
    { _id: '503', name: "Vasai-Virar", country: "India", countryCode: "IN" },
    { _id: '504', name: "Vellore", country: "India", countryCode: "IN" },
    { _id: '505', name: "Veraval", country: "India", countryCode: "IN" },
    { _id: '506', name: "Victoria", country: "Seychelles", countryCode: "SC" },
    { _id: '507', name: "Vidisha", country: "India", countryCode: "IN" },
    { _id: '508', name: "Vientiane", country: "Laos", countryCode: "LA" },
    { _id: '509', name: "Vijayawada", country: "India", countryCode: "IN" },
    { _id: '510', name: "Virar", country: "India", countryCode: "IN" },
    { _id: '511', name: "Visakhapatnam", country: "India", countryCode: "IN" },
    { _id: '512', name: "Vizianagaram", country: "India", countryCode: "IN" },
    { _id: '513', name: "Warangal", country: "India", countryCode: "IN" },
    { _id: '514', name: "Wardha", country: "India", countryCode: "IN" },
    { _id: '515', name: "Washington", country: "USA", countryCode: "US" },
    { _id: '516', name: "Wellington", country: "New Zealand", countryCode: "NZ" },
    { _id: '517', name: "Windhoek", country: "Namibia", countryCode: "NA" },
    { _id: '518', name: "Wuhan", country: "China", countryCode: "CN" },
    { _id: '519', name: "Yamoussoukro", country: "Côte d'Ivoire", countryCode: "CI" },
    { _id: '520', name: "Yamunanagar", country: "India", countryCode: "IN" },
    { _id: '521', name: "Yangon", country: "Myanmar", countryCode: "MM" },
    { _id: '522', name: "Yavatmal", country: "India", countryCode: "IN" },
    { _id: '523', name: "Yerevan", country: "Armenia", countryCode: "AM" },
    { _id: '524', name: "Yogyakarta", country: "Indonesia", countryCode: "ID" },
    { _id: '525', name: "Yokohama", country: "Japan", countryCode: "JP" },
    { _id: '526', name: "Zhongshan", country: "China", countryCode: "CN" },
  ]);
  const [loading, setLoading] = useState(false);
  const [searchTerm, setSearchTerm] = useState('');

  useEffect(() => {
    setLoading(false);
  }, []);

  const filteredCities = cities.filter(city =>
    city.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
    city.country.toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <div className="surface-card w-full p-5 sm:p-6 dark:bg-slate-900/70 dark:border-slate-700/50">
      <div className="mb-4 flex items-center justify-between gap-3">
        <div>
          <p className="text-xs font-semibold uppercase tracking-[0.28em] text-teal-600 dark:text-teal-400">Quick picks</p>
          <h2 className="mt-1 text-2xl font-bold text-slate-900 dark:text-white">Popular Cities</h2>
        </div>
        <span className="rounded-full border border-slate-200 bg-white/70 px-3 py-1 text-xs font-semibold text-slate-700 dark:border-slate-700/50 dark:bg-slate-800/70 dark:text-slate-300">
          {filteredCities.length}
        </span>
      </div>

      <input
        type="text"
        placeholder="Filter cities..."
        value={searchTerm}
        onChange={(e) => setSearchTerm(e.target.value)}
        className="focus-ring mb-4 w-full rounded-2xl border border-slate-300/70 bg-white px-4 py-3 text-slate-900 placeholder:text-slate-400 dark:border-slate-600/50 dark:bg-slate-800 dark:text-white dark:placeholder:text-slate-500"
      />

      {loading ? (
        <div className="py-8 text-center text-sm muted-text dark:text-slate-400">Loading cities...</div>
      ) : (
        <div className="max-h-[28rem] space-y-3 overflow-y-auto pr-1">
          {filteredCities.map((city) => (
            <button
              key={city._id}
              onClick={() => onCitySelect(city.name)}
              className="group w-full rounded-3xl border border-slate-200/80 bg-white/80 px-4 py-3 text-left text-sm transition hover:-translate-y-0.5 hover:border-teal-300 hover:bg-white hover:shadow-lg dark:border-slate-700/50 dark:bg-slate-800/60 dark:hover:bg-slate-700/80 dark:hover:border-teal-500/50"
            >
              <div className="flex items-center justify-between gap-3">
                <div>
                  <div className="font-semibold text-slate-900 transition group-hover:text-teal-700 dark:text-white dark:group-hover:text-teal-300">{city.name}</div>
                  <div className="text-xs muted-text dark:text-slate-400">{city.country}</div>
                </div>
                <div className="rounded-full bg-slate-100 px-2.5 py-1 text-[11px] font-semibold uppercase tracking-wide text-slate-500 dark:bg-slate-700/70 dark:text-slate-300">
                  Select
                </div>
              </div>
            </button>
          ))}
        </div>
      )}
    </div>
  );
};

export default CityList;
